# Generated by Django 5.0.3 on 2024-04-01 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging_system', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
